Documentacion/Instructivos/basedatos-inicial.md
Documentacion/Instructivos/clonacion-inicial.md
Documentacion/Instructivos/issues-branchs.md

Instructivos traidos desde la Wiki al repo

traer instructivos de wiki

---

frontend/temiro_angular/src/app/home/registro/registro.component.css
frontend/temiro_angular/src/app/home/registro/registro.component.html

Se sacaron las variables utilizadas en la hoja de estilo.

Arreglo hojas de estilos

---

frontend/temiro_angular/src/app/app-routing.module.ts
frontend/temiro_angular/src/app/home/navbar/navbar.component.html
frontend/temiro_angular/src/app/home/registro/registro.component.css

Se comento código de hoja de estilo css del componente registro que no se utilizaba y se corrigió que al iniciar el sitio aparezca el componente body.

#61 TK09-7 crear ruteo angular del componente registro.

---

Documentacion/RES_IEEE830.md

ultimos cambios en documento ieee830

38-tk90-1-mantener-actualizado-el-documento-ieee830

---

Documentacion/Sprint 1/1. Sprint Planing.md
Documentacion/Sprint 1/2. Daily Scrum Meeting 1.md
Documentacion/Sprint 1/3. Daily Scrum Meeting 2.md
Documentacion/Sprint 1/4. Daily Scrum Meeting 3.md
Documentacion/Sprint 1/5. Daily Scrum Meeting 4.md
Documentacion/Sprint 1/6. Sprint Review y Retrospective.md
README.md
frontend/temiro_angular/package-lock.json
frontend/temiro_angular/src/app/login/login.component.css

Ingresar cambios desde "develop" a la "main" en el Sprint 1

Develop a main

---

app.module.ts
db.json
home.module.ts
login.component.html
login.component.ts
registro.component.html
registro.component.ts

Iniciar el JSON Server con el comando : json-server --watch db.json para visualizarlo desde el navegador ejecutar en el puerto 3000 http://localhost:3000/
en Resources se creo la matriz /RegistroUsuarios que almacena la informacion enviada desde el Registro.component.ts por medio del Modulo HttpClient se alamacena en el archivo raiz db.json :
°Fullname.
°email.
°username.
°password.

JSON Server

---

frontend/temiro_angular/src/app/app.module.ts
frontend/temiro_angular/src/app/home/faq/faq.component.css
frontend/temiro_angular/src/app/home/faq/faq.component.html

La pantalla de las respuestas a las preguntas ya esta visible.

Arreglo de la funcionalidad del componente faq

---

Documentacion/Instructivos/abm-tablas-django.md
backend/temiro_django/PROYTM/settings.py
backend/temiro_django/admintm/forms.py
backend/temiro_django/admintm/static/css/style.css
backend/temiro_django/admintm/templates/editar.html
backend/temiro_django/admintm/templates/mostrar.html
backend/temiro_django/admintm/templates/producto.html
backend/temiro_django/admintm/urls.py
backend/temiro_django/admintm/views.py
backend/temiro_django/webapi/admin.py
backend/temiro_django/webapi/models.py
backend/temiro_django/webapi/views.py

- Se agrega instructivo sobre al ABM de productos y servicios en el backend
- Se inicia un ABM de productos en la aplicación "admintm" del backend
- Se hacen mejoras en el modelo de datos de Django

abm productos y servicios

---

Documentacion/Instructivos/rolesUsuario.md

Se realizó un instructivo de como se realizó la creación de roles en django y la actualización en la base de datos.

Instructivo creacion de Roles Users Django

---

frontend/temiro_angular/src/app/home/login/login.component.html
frontend/temiro_angular/src/app/home/login/login.component.ts
frontend/temiro_angular/src/app/home/registro/registro.component.html
frontend/temiro_angular/src/app/home/registro/registro.component.ts

Se reviso que los formularios de login y registro tengan “input types” acorde al dato que se va a ingresar. Se reviso que informen al usuario con mensajes personalizados, se realizaron las validaciones mediante formBuilder.

Validación de Formularios

---

backend/temiro_django/PROYTM/settings.py
backend/temiro_django/PROYTM/urls.py
backend/temiro_django/webapi/serializers.py
backend/temiro_django/webapi/urls.py
backend/temiro_django/webapi/views.py

Se da comienzo a la API, definiendo clases de serializacion para las clases del modelo Usuario y Productos, y vistas de esas dos clases, tanto para listar a todos los elementos como para modificar a uno de ellos. Esto se realiza usando el Django REST Framework.

inicio webapi usuarios y productos

---

frontend/temiro_angular/src/app/dashboardadmin/dashboardadmin.component.html

arreglo iconos

---

frontend/temiro_angular/src/app/home/login/login.component.css
frontend/temiro_angular/src/app/home/login/login.component.html
frontend/temiro_angular/src/app/home/login/login.component.ts
frontend/temiro_angular/src/app/home/registro/registro.component.css
frontend/temiro_angular/src/app/home/registro/registro.component.html
frontend/temiro_angular/src/app/home/registro/registro.component.ts

Validacion de formularios

---

Documentacion/Sprint 2/4 Daily Scrum Meeeting3.md
Documentacion/Sprint 2/5 Sprint Review y Retrospective.md
Documentacion/Sprint 3/Sprint Plannig.md

Se completa el Sprint 2 con las dailys correspondientes y se Incorpora el Sprint Planning del Sprint 3.

Se Ingresa Doc.

---

backend/temiro_django/PROYTM/settings.py
backend/temiro_django/webapi/models.py
backend/temiro_django/webapi/serializers.py
backend/temiro_django/webapi/urls.py
backend/temiro_django/webapi/views.py

- Se crea un metodo basico de autenticacion en el modelo (clase "Usuario")
- Se crean las vistas para login, logout, registro, agregar y borrar productos

metodos para login y registro

---

frontend/temiro_angular/package.json
frontend/temiro_angular/proxy.conf.json
frontend/temiro_angular/src/app/home/login/login.component.html
frontend/temiro_angular/src/app/home/login/login.component.ts

-Se agregaron los archivos proxy.conf.json, se modifico del package.json las lineas  "start": "ng serve --proxy-config proxy.conf.json",Se inicia mediante el comando npm start en lugar de ng serve. Se modifico los archivos login.component.html y login.component.ts, falta solucionar la validacion del login se trae los datos de usuario del backend pero no valida.

Conexión con el backend para el inicio de sesión

---

backend/database/insertar-datos.sql
backend/temiro_django/PROYTM/settings.py
backend/temiro_django/webapi/models.py
backend/temiro_django/webapi/views.py
frontend/temiro_angular/src/app/dashboardadmin/formu-productos/formu-productos.component.css
frontend/temiro_angular/src/app/dashboardadmin/formu-productos/formu-productos.component.html
frontend/temiro_angular/src/app/dashboardadmin/formu-productos/formu-productos.component.ts
frontend/temiro_angular/src/app/dashboardadmin/indice-adm/indice-adm.component.html
frontend/temiro_angular/src/app/home/login/login.component.css
frontend/temiro_angular/src/app/home/login/login.component.html
frontend/temiro_angular/src/app/home/login/login.component.ts
frontend/temiro_angular/src/app/home/registro/registro.component.css
frontend/temiro_angular/src/app/home/registro/registro.component.html
frontend/temiro_angular/src/app/home/registro/registro.component.ts
frontend/temiro_angular/src/assets/js/carrito-legacy.js

- Se conecta el formulario del registro con el backend (se tuvo que generar otro formulario al vuelo porque los campos no coinciden, y para poder generar el ID, que se genera de forma aleatoria en el frontend)
- Se conecta el formulario del login con el backend. Durante el login se verifica si el usaurio es "admin", en cuyo caso se lo dirige al "indiceadm", y para el resto de los usuarios se lo dirije al "indice" del dashboard.
- Se conecta el formulario para alta de productos con el backend. Se coloca un acceso a este formulario desde el "indiceadm" en el icono de los lentes negros.

conexion con backend 3 formularios

---

frontend/temiro_angular/src/app/home/login/login.component.css
frontend/temiro_angular/src/app/home/login/login.component.html
frontend/temiro_angular/src/app/home/login/login.component.ts

los avisos personalizados de error aparecen solamente cuando el usuario hace clic sobre el campo, desaparecen cuando están correctos los datos ingresados.

Cambios Login mensajes al usuario 

---

frontend/temiro_angular/src/app/home/faq/faq.component.css
frontend/temiro_angular/src/app/home/faq/faq.component.html

Para que se vea mejor y cumpla su función mas eficientemente.

Se arreglo el faq 

---

backend/temiro_django/webapi/urls.py
backend/temiro_django/webapi/views.py
frontend/temiro_angular/src/app/dashboardadmin/formu-productos/formu-productos.component.html
frontend/temiro_angular/src/app/dashboardadmin/formu-productos/formu-productos.component.ts

Se Agrego la función modificar producto con esto queda completo el ABM-Productos.

ABM-Productos

---

frontend/temiro_angular/src/app/app-routing.module.ts
frontend/temiro_angular/src/app/dashboard/dashboard.module.ts
frontend/temiro_angular/src/app/dashboard/indice/indice.component.html
frontend/temiro_angular/src/app/dashboard/perfil/perfil.component.css
frontend/temiro_angular/src/app/dashboard/perfil/perfil.component.html
frontend/temiro_angular/src/app/dashboard/perfil/perfil.component.spec.ts
frontend/temiro_angular/src/app/dashboard/perfil/perfil.component.ts

Se agregó Formulario para modificar Datos de Usuario.

Se agrego componente para modificar perfil de usuario
